In [1]:
import pandas as pd
data = pd.read_csv("iris.csv")
data = data.drop("Id", axis= 1)

In [2]:
x = data.drop("Species" , axis =1)
x.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [4]:
y = data["Species"]
y.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size = 0.3)

# K-Nearest Neighbors

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
knn.score(x_test, y_test)

1.0

# Random Forest

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9777777777777777

# Naive Bayes

In [13]:
from sklearn.naive_bayes import GaussianNB
nb  = GaussianNB()
nb.fit(x_train, y_train)
nb.score(x_test, y_test)

0.9777777777777777

# Support Vector Machine

In [14]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)


1.0

# Cross Validation
#### To find the best algorithm for the data set.

In [25]:
from sklearn.model_selection import cross_val_score

### K-Nearest Neighbors

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn , x, y, cv =5)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [27]:
cross_val_score(knn , x, y, cv =5).mean()

np.float64(0.9733333333333334)

### Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
cross_val_score(rf, x, y, cv =5)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [29]:
cross_val_score(rf, x, y, cv =5).mean()

np.float64(0.96)

### Naive Bayes

In [30]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
cross_val_score(nb, x, y, cv = 5)

array([0.93333333, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [31]:
cross_val_score(nb, x, y, cv = 5).mean()

np.float64(0.9533333333333334)

### Support Vector Machine

In [32]:
from sklearn.svm import SVC
svm = SVC()
cross_val_score(svm,x, y,cv=5)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [33]:
cross_val_score(svm,x, y,cv=5).mean()

np.float64(0.9666666666666666)