In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y)
x_train

array([ 5, 17,  9, 16,  8, 18,  7, 11,  1,  3, 10, 13,  2,  4, 12])

In [5]:
len(x_train)

15

In [6]:
len(x_test)

5

In [7]:
len(y_test)

5

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2)
x_train

array([ 3, 15,  5, 18,  8,  1, 19, 11,  9, 12,  7, 13,  6, 10,  2, 16])

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2, random_state =5)
x_train

array([13,  2, 12, 11, 14, 19,  8,  5,  9, 10,  1, 17,  7, 16, 15,  4])

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2, shuffle = False)
x_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])